import type { AuditReport } from "@/lib/types"

interface Props {
  metadata: AuditReport["metadata"]
}

export function MetadataFooter({ metadata }: Props) {
  if (!metadata) return null

  const items = [
    { label: "Generated by",   value: metadata.generated_by },
    { label: "Schema version", value: metadata.schema_version },
    { label: "Audit ID",       value: metadata.audit_id },
    { label: "Generated at",   value: new Date(metadata.generated_at).toLocaleString() },
  ]

  return (
    <footer className="pt-12 mt-8 border-t border-[#262626] grid grid-cols-2 md:grid-cols-4 gap-y-5 gap-x-6">
      {items.map(({ label, value }) => (
        <div key={label}>
          <p className="font-mono text-[10px] uppercase tracking-[0.18em] text-[#3F3F3F] mb-1.5">
            {label}
          </p>
          <p className="font-mono text-[12px] text-[#A3A3A3] break-all">{value}</p>
        </div>
      ))}
    </footer>
  )
}
